version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: mkdir junit
      - run:
          command: node_modules/.bin/mocha test --mocha-junit-reporter
          environment:
            MOCHA_FILE: ./junit/test-result.xml
          when: always
      - store_test_result:
         path: ./junit
      - store_artifacts:
         path: ./junit  
